// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatDataMessage {
    #[prost(int64, tag = "1")]
    pub match_id: i64,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub slot: i64,
    #[prost(int64, tag = "4")]
    pub time: i64,
    #[prost(string, tag = "5")]
    pub unit: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatsData {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<ChatDataMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeDataMessage {
    #[prost(string, tag = "1")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub open: f64,
    #[prost(double, tag = "3")]
    pub high: f64,
    #[prost(double, tag = "4")]
    pub low: f64,
    #[prost(double, tag = "5")]
    pub close: f64,
    #[prost(double, tag = "6")]
    pub volume: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeData {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<TradeDataMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TweetDataMessage {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub fullname: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub replies: i64,
    #[prost(int64, tag = "7")]
    pub likes: i64,
    #[prost(int64, tag = "8")]
    pub retweets: i64,
    #[prost(string, tag = "9")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TweetData {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<TweetDataMessage>,
}
