[package]
name = "encoders-comparison"
version = "0.1.0"
edition = "2024"

[dependencies]
c4encoder = { package = "encoder", path = "../encoder" }
prost = "0.14.1"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.14.1"
